// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsD1Fic23pVsabVDlX1hd1uSyZWDrmsY',
    appId: '1:946554363939:web:adf3105cfde8e021eb5196',
    messagingSenderId: '946554363939',
    projectId: 'start-trip-8bb36',
    authDomain: 'start-trip-8bb36.firebaseapp.com',
    storageBucket: 'start-trip-8bb36.firebasestorage.app',
    measurementId: 'G-31GVH3G845',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJRPFnxGyQnJxlmDdUabvFPxgF9woOUs',
    appId: '1:946554363939:android:c29edd684a710e0aeb5196',
    messagingSenderId: '946554363939',
    projectId: 'start-trip-8bb36',
    storageBucket: 'start-trip-8bb36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzva1g61IRobd-XN8F4M6Z_KjUfrdoxM',
    appId: '1:946554363939:ios:82b5d03e74e3a587eb5196',
    messagingSenderId: '946554363939',
    projectId: 'start-trip-8bb36',
    storageBucket: 'start-trip-8bb36.firebasestorage.app',
    iosClientId: '946554363939-t228bfr21kmes371igf7ua64f61qd23s.apps.googleusercontent.com',
    iosBundleId: 'com.tripbuddy.tripBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzva1g61IRobd-XN8F4M6Z_KjUfrdoxM',
    appId: '1:946554363939:ios:82b5d03e74e3a587eb5196',
    messagingSenderId: '946554363939',
    projectId: 'start-trip-8bb36',
    storageBucket: 'start-trip-8bb36.firebasestorage.app',
    iosClientId: '946554363939-t228bfr21kmes371igf7ua64f61qd23s.apps.googleusercontent.com',
    iosBundleId: 'com.tripbuddy.tripBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsD1Fic23pVsabVDlX1hd1uSyZWDrmsY',
    appId: '1:946554363939:web:c9032769c7a95dd4eb5196',
    messagingSenderId: '946554363939',
    projectId: 'start-trip-8bb36',
    authDomain: 'start-trip-8bb36.firebaseapp.com',
    storageBucket: 'start-trip-8bb36.firebasestorage.app',
    measurementId: 'G-D9Q52PLPNC',
  );
}
